version: '2'
services:
  navitia:
    image: navitia/debian8_simple
    ports:
      - "8081:80"
    volumes:
      - /home/vagrant/data:/srv/ed/data
      - /tmp/log/tyr:/var/log/tyr
      - /tmp/log/kraken:/var/log/kraken
      - /tmp/log/jormungandr:/var/log/jormungandr
  explorer:
    build: ../ext/explorer
    command: python -m http.server
    ports:
      - "8082:8000"
    volumes:
      - ../ext/explorer:/code
