version: '2'
services:
  navitia:
    image: navitia/debian8_simple
    volumes:
      - /home/vagrant/data:/srv/ed/data
    environment:
      SERVICE_NAME: 'navitia'
      SERVICE_CHECK_HTTP: '/'
      SERVICE_CHECK_INTERVAL: '5s'
  explorer:
    image: beeksiwaais/navitia-explorer
    environment:
      HOST: 'localhost'
      NAVITIA: 'http://localhost:80/v1/'
      TYR: 'http://localhost:80/v0/'
      KEY: ''
      COVERAGE: 'default'
      SERVICE_NAME: 'explorer'
      SERVICE_CHECK_HTTP: '/'
      SERVICE_CHECK_INTERVAL: '5s'
  consul:
    command: -server -bootstrap
    image: progrium/consul:latest
    container_name: 'consul'
    environment:
      SERVICE_53_IGNORE: 'yes'
      SERVICE_8300_IGNORE: 'yes'
      SERVICE_8301_IGNORE: 'yes'
      SERVICE_8302_IGNORE: 'yes'
      SERVICE_8400_IGNORE: 'yes'
      SERVICE_8500_NAME: 'consul-admin_infra'
  registrator:
    command: "-internal consul://consul:8500"
    image: gliderlabs/registrator:latest
    container_name: 'registrator'
    links:
      - "consul"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
